name: Run Google Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
            git clone https://github.com/google/googletest.git
            cd googletest
            cmake -Bbuild
            cmake --build build 
            sudo cmake --build build --target install
    - name: Build & run tests
      run: |
            mkdir build 
            cd build
            cmake ..
            make 
            ./tests/LongArithmeticTests
